CREATE TABLE `arbitrage_opportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventId` varchar(64) NOT NULL,
	`sport` varchar(32) NOT NULL,
	`league` varchar(32) NOT NULL,
	`matchup` varchar(256) NOT NULL,
	`eventTime` timestamp NOT NULL,
	`bookA` varchar(64) NOT NULL,
	`bookB` varchar(64) NOT NULL,
	`outcomeA` varchar(256) NOT NULL,
	`oddsA` decimal(6,2) NOT NULL,
	`impliedProbabilityA` decimal(5,4) NOT NULL,
	`outcomeB` varchar(256) NOT NULL,
	`oddsB` decimal(6,2) NOT NULL,
	`impliedProbabilityB` decimal(5,4) NOT NULL,
	`totalImpliedProbability` decimal(5,4) NOT NULL,
	`arbitragePercentage` decimal(5,4) NOT NULL,
	`profitPercentage` decimal(5,4) NOT NULL,
	`stakeA` decimal(8,2) NOT NULL,
	`stakeB` decimal(8,2) NOT NULL,
	`guaranteedProfit` decimal(8,2) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`expiresAt` timestamp NOT NULL,
	`source` varchar(64) NOT NULL DEFAULT 'api',
	`lastUpdated` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `arbitrage_opportunities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_arbitrage_trades` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`arbitrageId` int NOT NULL,
	`stakeA` decimal(8,2) NOT NULL,
	`stakeB` decimal(8,2) NOT NULL,
	`totalStake` decimal(8,2) NOT NULL,
	`bookABetId` varchar(128),
	`bookBBetId` varchar(128),
	`executedAt` timestamp,
	`resultA` enum('pending','won','lost','void') NOT NULL DEFAULT 'pending',
	`resultB` enum('pending','won','lost','void') NOT NULL DEFAULT 'pending',
	`winningsA` decimal(8,2),
	`winningsB` decimal(8,2),
	`totalWinnings` decimal(8,2),
	`actualProfit` decimal(8,2),
	`status` enum('pending','executed','completed','failed') NOT NULL DEFAULT 'pending',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_arbitrage_trades_id` PRIMARY KEY(`id`)
);
